#!/bin/bash -ex

source /usr/local/src/gitlab.conf

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
# install new git from wheezy-backports

apt-get -y remove git-core
echo "deb http://ftp.de.debian.org/debian/ wheezy-backports main" >> /etc/apt/sources.list.d/sources.list
apt-get -y update
apt-get -y -t wheezy-backports install git

unset HTTP_PROXY

