#!/bin/bash -ex

source /usr/local/src/gitlab.conf

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
# install ruby
cd $SRC
curl --progress ftp://ftp.ruby-lang.org/pub/ruby/stable-snapshot.tar.gz | tar xz
cd ruby-*
./configure --prefix=/usr --disable-install-rdoc
make
make install

# update and install gems
GEMOPTS="--no-rdoc --no-ri"

gem update  $GEMOPTS --system
gem update  $GEMOPTS
gem install $GEMOPTS rake
gem install $GEMOPTS bundler
gem install $GEMOPTS charlock_holmes --version $VERSION_CHARLOCK_HOLMES
unset HTTP_PROXY

