#!/bin/bash -ex

source /usr/local/src/gitlab.conf

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
# install ruby
curl --progress ftp://ftp.ruby-lang.org/pub/ruby/stable-snapshot.tar.gz | tar xz
cd ruby-*
./configure --disable-install-rdoc
make
sudo make install

# update and install gems
gem update --system --no-ri --no-rdoc
gem update --no-ri --no-rdoc
gem install bundler --no-ri --no-rdoc
gem install charlock_holmes --version $VERSION_CHARLOCK_HOLMES --no-ri --no-rdoc
unset HTTP_PROXY

