#!/bin/bash -ex

source /usr/local/src/gitlab.conf

/etc/init.d/postgresql start

# Create a user for GitLab
sudo -u postgres createuser -D -R -S $DB_USER

# Create the GitLab production database
sudo -u postgres createdb -O $DB_USER $DB_NAME
