#!/bin/bash -ex

source /usr/local/src/gitlab.conf

# setup unicorn and nginx
exec_git "mv $GITLAB_CONF/unicorn.rb.example $GITLAB_CONF/unicorn.rb"

rm /etc/nginx/sites-enabled/default

sed -i "s|YOUR_SERVER_FQDN|$DOMAIN|" /etc/nginx/sites-available/gitlab
ln -s /etc/nginx/sites-available/gitlab /etc/nginx/sites-enabled/gitlab

